version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    restart: unless-stopped
    command: npm start

  analytics:
    build: .
    working_dir: /app
    command: npm run analytics
    restart: unless-stopped
    cron: "0 2 * * *"
